apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  labels:
    name: nextcloud
spec:
  ports:
    - name: apache
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nextcloud
